### ISSUE TITLE
Import math.js library into Javascript plugin

### ISSUE THREAD

**Issue by jghager** [glideapps/glide-code-columns#82]
I'm hoping to do some trigonometry math with some javascript, but as far as I can tell, only basic math is supported.

I'm hoping that I can do what I I'd like if the math.js library is included.

**Comment by dvdsgl** [comment]
You should be able to import it yourself. We will not add it to the main JavaScript plugin.

What are you trying to do? Maybe we need a separate mathjs plugin?

**Comment by jghager** [comment]
I'm trying to build a geo based app which uses a lot of trig.  I do a lot of geocaching, as well as some minor maintenance with our mapping software at work, so it's a bit of a pet project to see what I can pull off with glide.  I'm currently replicating haversine logic over 40 or so columns, plus some other columns to calculate things such as bearing and what not, but it would be a lot easier with a single function and a few parameters.  I'd also like to see if I can figure out how to calculate speed.  I'm sure I could condense what I have now with the existing math columns, since they already do what I need.

I'll play around some more, but I keep getting the following error when I try to add an import in the javascript plugin:
"SyntaxError: Cannot use import statement outside a module"

Javascript isn't my first language outside of maintaining it, so I'm not familiar with all of the nuances.

If I'm picturing what you mean with a mathjs plugin, I'm not sure if it would work in this case, since I'd like to customize the rest of the function with other code logic, however, I would love a plugin where I could just pass in a user entered or dynamic math formula, so it could be useful.

It's all just a big experiment and a learning experience for me.

**Comment by dvdsgl** [comment]
Solved here: https://community.glideapps.com/t/how-to-import-code-packages-in-the-javascript-column/34466
